# Generated by Django 5.2.7 on 2025-10-05 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["severity"], name="logs_app_lo_severit_ddb200_idx"
                    ),
                    models.Index(
                        fields=["source"], name="logs_app_lo_source_fa879b_idx"
                    ),
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="logs_app_lo_timesta_b7453b_idx",
                    ),
                ],
            },
        ),
    ]
